dist: bionic

language: c

services:
  - docker

matrix:
  include:
  - os: linux
    env: NIMBRANCH=devel ARCH=64
  # - os: linux
  #   env: NIMBRANCH=devel ARCH=32
  - os: osx
    env: NIMBRANCH=devel ARCH=64
  - os: windows
    env: NIMBRANCH=devel ARCH=64
  - os: windows
    env: NIMBRANCH=devel ARCH=32
  # - os: linux
  #   env: NIMBRANCH=devel ARCH=armv7l
  - os: linux
    env: NIMBRANCH=devel ARCH=arm64

  - os: linux
    env: NIMBRANCH=version-1-4 ARCH=64
  # - os: linux
  #   env: NIMBRANCH=version-1-4 ARCH=32
  - os: osx
    env: NIMBRANCH=version-1-4 ARCH=64
  - os: windows
    env: NIMBRANCH=version-1-4 ARCH=64
  - os: windows
    env: NIMBRANCH=version-1-4 ARCH=32
  # - os: linux
  #   env: NIMBRANCH=version-1-4 ARCH=armv7l
  - os: linux
    env: NIMBRANCH=version-1-4 ARCH=arm64

  - os: linux
    env: NIMBRANCH=version-1-2 ARCH=64
  # - os: linux
  #   env: NIMBRANCH=version-1-2 ARCH=32
  - os: osx
    env: NIMBRANCH=version-1-2 ARCH=64
  - os: windows
    env: NIMBRANCH=version-1-2 ARCH=64
  - os: windows
    env: NIMBRANCH=version-1-2 ARCH=32
  # - os: linux
  #   env: NIMBRANCH=version-1-2 ARCH=armv7l
  - os: linux
    env: NIMBRANCH=version-1-2 ARCH=arm64

  - os: linux
    env: NIMBRANCH=version-1-0 ARCH=64
  # - os: linux
  #   env: NIMBRANCH=version-1-0 ARCH=32
  - os: osx
    env: NIMBRANCH=version-1-0 ARCH=64
  - os: windows
    env: NIMBRANCH=version-1-0 ARCH=64
  - os: windows
    env: NIMBRANCH=version-1-0 ARCH=32
  # - os: linux
  #   env: NIMBRANCH=version-1-0 ARCH=armv7l
  - os: linux
    env: NIMBRANCH=version-1-0 ARCH=arm64

addons:
  apt:
    update: true
    packages:
      - qemu-user
      - netbase

before_cache:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew cleanup
  fi

cache:
  directories:
    - mingw
    - nodejs
    - $HOME/Library/Caches/Homebrew

script:
  - export OSVAR="$TRAVIS_OS_NAME"
  - export BUILDDIR="$TRAVIS_BUILD_DIR"
  - ./nightest.sh
